### ISSUE TITLE
work out what s3o "v2" stuff is about and update accordingly.

### ISSUE THREAD

**Issue by ghost** [Financial-Times/ft-s3o-go#3]

**Comment by matthew-andrews** [comment]
v2 is a security update … 😁

**Comment by matthew-andrews** [comment]
you need to use the host
https://github.com/Financial-Times/s3o-middleware/pull/9/files

**Comment by matthew-andrews** [comment]
highly recommend using the `post` option because otherwise tokens end up in access logs^^

**Comment by ghost** [comment]
thanks Matt. I spoke to Luke and I now understand.  I'm using v2 properly now I think. will close this and look at using POST.

**Comment by matthew-andrews** [comment]
☺️
